# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = '$custom$time$all'

[battery]
disabled = true

[line_break]
disabled = true

[time]
disabled = false
format = '[$time](yellow) in '

[package]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[nodejs]
version_format = 'v${major}'

[custom.is_bash]
description = "Indicates when in BASH shell"
command = "echo ''"
when = '[ "$STARSHIP_SHELL" == "bash" ]'
format = '[ $output ](bg:purple black) '

[custom.is_fish]
description = "Indicates when in FISH shell"
command = 'echo "🐟"'
when = 'test "$STARSHIP_SHELL" = "fish"'
format = '[ $output ](bg:blue black) '
