# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = '$custom$is_bash$time$all'

[battery]
disabled = true

[line_break]
disabled = true

[time]
disabled = false
format = '[$time](yellow) in '

[package]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# [custom.incognito]
# command = 'echo "󱀣"'
# when = "[[ -z \"$HISTFILE\" ]]"
# shell = ["/Users/vmello/dotfiles/test.sh"]
# when = true
# format = '[ $output ](bg:none purple) '

# Indicates when in bash shell.
[custom.bash]
command = "echo 'bash'"
when = '[ "$STARSHIP_SHELL" == "bash" ]'
format = '[ $output ](bg:purple black) '
