# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = '$custom$time$all'

[battery]
disabled = true

[line_break]
disabled = true

[time]
disabled = false
format = '[$time](yellow) in '

[package]
disabled = true

[perl]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[nodejs]
version_format = 'v${major}'

[custom.is_bash]
description = "Indicates when in BASH shell"
command = "echo ''"
shell = ['bash']
when = 'test "$STARSHIP_SHELL" = "bash"'
format = '[ $output ](bg:purple black) '

[custom.is_fish]
description = "Indicates when in FISH shell"
command = 'echo "🐟"'
when = 'test "$STARSHIP_SHELL" = "fish"'
shell = ['bash']
format = '[ $output ](bg:blue black) '

[custom.is_private]
description = "Indicates when in ZSH is running without $HISTFILE"
command = 'echo "PRIVATE"'
when = '[ -n "$NOHISTFILE" ]'
format = '[ $output ](bg:purple black) '
